# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: 최다은 포트폴리오 # Website name
baseURL: "https://ddaaan.github.io/" # Website URL

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

params:
  description: "전북대학교 IT정보공학과 최다은 포트폴리오 | 전북대 LLM·프론트엔드 프로젝트, 논문, 수상"
  keywords: ["전북대학교", "전북대", "JBNU", "최다은", "포트폴리오", "컴퓨터", "AI", "백엔드"]
  images: ["/uploads/og-default.png"]

############################
## PAGE OPTIONS
############################

cascade:
  # Blog post options
  - _target:
      path: /post/**
    editable: true
    reading_time: true
    commentable: true
    show_related: true
    show_breadcrumb: true

############################
## LANGUAGE
############################

defaultContentLanguage: "ko"
hasCJKLanguage: true
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep
minify:
  _merge: deep
