main:
  - name: Home
    url: /
    weight: 10

  - name: About
    url: about/
    weight: 20

  - name: Projects
    url: projects/
    weight: 30

  - name: Contact
    url: "#contact"     
    weight: 40

  # ── About 의 하위 메뉴들
  - name: Education
    url: about/#education          
    parent: About
    weight: 21

  - name: Experience
    url: about/#experience        
    parent: About
    weight: 22

  - name: Awards
    url: about/#accomplishments  
    parent: About
    weight: 23

  - name: Résumé (PDF)
    url: files/resume.pdf        
    parent: About
    weight: 24

  # ── Projects 의 하위 메뉴들
  - name: Web
    url: projects/#web
    parent: Projects
    weight: 31

  - name: Embedded
    url: projects/#embedded
    parent: Projects
    weight: 32
