main:
  - name: 홈
    url: /
    weight: 10

  - name: 소개
    url: about/
    weight: 20
    identifier: about

  - name: 경험
    url: experience/
    weight: 30

  - name: 프로젝트
    url: project/
    weight: 40

  - name: 논문
    url: publication/
    weight: 50

  - name: 수상
    url: accomplishments/
    weight: 60

  - name: 연락처
    url: contact/
    weight: 70

  # ── About 의 하위 메뉴들
  - name: 학력
    url: about/#education          
    parent: about
    weight: 21

  - name: 경력
    url: about/#work         
    parent: about
    weight: 22

  - name: 경험
    url: about/#experience        
    parent: about
    weight: 23

  # - name: Résumé (PDF)
  #   url: files/resume.pdf        
  #   parent: About
  #   weight: 24